version = 0.1

[default.deploy.parameters]
stack_name = "update-tenant-stats"
resolve_s3 = true
s3_prefix = "update-tenant-stats"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MongoUri=\"\""
image_repositories = []
