AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Backend Lambda for Flatmates CRM

Globals:
  Function:
    Timeout: 30

Resources:
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: server-BackendFunction-mrdpEAffrjHV
      Handler: server.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 512
      Environment:
        Variables:
          MONGO_URI: !Ref MongoUri
          FRONTEND_URL: !Ref FrontendUrl
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Parameters:
  MongoUri:
    Type: String
  FrontendUrl:
    Type: String

Outputs:
  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
