name: Deploy Backend API Lambda

on:
  push:
    branches:
      - main

jobs:
  backendApiLambda:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install SAM CLI
        run: pip install aws-sam-cli

      - name: Install Dependencies
        run: npm install

      - name: Build with SAM
        run: sam build --template template.yaml

      - name: Deploy with SAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-north-1"
        run: |
          sam deploy --stack-name server \
            --template-file .aws-sam/build/template.yaml \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              MongoUri="${{ secrets.MONGO_URI }}" \
              FrontendUrl="${{ secrets.FRONTEND_URL }}" \
            --region $AWS_REGION \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --resolve-s3 \
            --force-upload
